import type { ColumnType, Generated } from 'kysely'
import type { RichTextDoc } from '@daily-report/types'

/**
 * Kysely interface for the *application* tables.
 *
 * ⚠️ The better-auth tables (`user`, `session`, `account`, `verification`)
 * are deliberately absent here: their columns are in quoted camelCase
 * ("emailVerified", "userId"), and the CamelCasePlugin mounted on the Kysely
 * instance would rewrite them to snake_case. To query them, go through
 * `pool.query()` (see `src/db/index.ts`).
 *
 * ⚠️ The CamelCasePlugin also translates **table names**: the `dailyNotes`
 * key below does target the `daily_notes` table, and `noteDate` the
 * `note_date` column. Writing the keys in snake_case here would produce
 * `daily__notes` in SQL.
 */
export interface Database {
  projects: ProjectsTable
  dailyNotes: DailyNotesTable
  attachments: AttachmentsTable
}

export interface ProjectsTable {
  id: Generated<string>
  userId: string
  name: string
  /** `NULL` while the project is active — see migration 001. */
  archivedAt: Date | null
  createdAt: Generated<Date>
}

export interface DailyNotesTable {
  id: Generated<string>
  userId: string
  projectId: string
  /**
   * `DATE` on the Postgres side, a `YYYY-MM-DD` string on the TypeScript side
   * — the parser set up in `src/db/index.ts` stops `pg` from turning it into
   * a `Date` object.
   */
  noteDate: string
  title: string
  content: ColumnType<RichTextDoc, RichTextDoc, RichTextDoc>
  contentText: string
  /**
   * `regconfig` config name (`french`/`english`), fixed at creation by a SQL
   * trigger from the account's language — never written by application code.
   */
  searchLanguage: Generated<string>
  /** Column generated by Postgres from `title`/`contentText` — read-only. */
  searchVector: ColumnType<string, never, never>
  createdAt: Generated<Date>
  updatedAt: Generated<Date>
}

export interface AttachmentsTable {
  id: Generated<string>
  noteId: string
  /** Opaque storage key — see `src/storage/driver.ts`. */
  storageKey: string
  filename: string
  mimeType: string
  /**
   * `BIGINT` on the Postgres side: `pg` returns it as a string to avoid
   * losing precision. Converted back at the HTTP boundary.
   */
  sizeBytes: ColumnType<string, number, number>
  createdAt: Generated<Date>
}
