-- Full database schema, in a single script.
--
-- As long as the model isn't frozen and there's no production data to
-- preserve, a schema change happens here, in this file — not through an
-- additive migration stacked on top. Touching the schema therefore requires a
-- `pnpm db:reset`. Once the database holds data worth keeping, we go back to
-- numbered additive migrations and stop re-editing this file once applied.
--
-- better-auth tables (user, session, account, verification): generated by
-- `pnpm dlx @better-auth/cli generate --config src/auth.ts`, carried over here
-- as-is. Regenerate and fold the result back into this file after any
-- better-auth plugin addition or `additionalFields` change. Columns in
-- quoted camelCase: these tables never go through the Kysely instance
-- (CamelCasePlugin) — see src/db/index.ts.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "language" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

-- Full-text search: extensions and helper function, set up before the
-- application tables since daily_notes needs them as soon as it's created.

CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- unaccent() isn't declared IMMUTABLE by Postgres (it depends on search_path
-- to find its dictionary), which rules it out in a generated column or
-- functional index. This fixed-search_path wrapper is the standard
-- workaround.
CREATE OR REPLACE FUNCTION f_unaccent(text)
RETURNS text AS $$
  SELECT unaccent('unaccent', $1)
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
   SET search_path = public, pg_catalog;

-- A project holds an account's notes (a job site, a client...); an account
-- has at least one.

CREATE TABLE projects (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  -- Soft delete: set when archived, NULL otherwise. Archiving is reversible
  -- (unlike deleting the project outright), so it's a timestamp to toggle,
  -- not a row to remove.
  archived_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX projects_user_idx ON projects (user_id, created_at);

-- The journal's notes: one per project and per date — the UNIQUE
-- (project_id, note_date) constraint IS the business rule, it lives here and
-- not in application code that could be bypassed. user_id stays on the row:
-- routes depend on it to filter directly on it (see CLAUDE.md, the only
-- authorization safeguard), even though it follows from project_id.
--
-- Each note is indexed in the language of the account that wrote it rather
-- than fixed French (search_language, frozen at creation by the trigger
-- below): the language dictionary changes stemming, not just stop words.
-- Title weighted 'A', content weighted 'B': paves the way for a future
-- relevance sort (ts_rank). STORED: Postgres maintains search_vector on its
-- own on every write to title/content_text.
CREATE TABLE daily_notes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  note_date       DATE NOT NULL,
  title           TEXT NOT NULL DEFAULT '',
  -- TipTap document, exactly as the editor serializes it.
  content         JSONB NOT NULL,
  -- Flattened text, recomputed server-side on every write. Feeds today's list
  -- excerpts, and full-text search later.
  content_text    TEXT NOT NULL DEFAULT '',
  search_language regconfig NOT NULL DEFAULT 'french',
  search_vector   tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector(search_language, f_unaccent(title)), 'A') ||
    setweight(to_tsvector(search_language, f_unaccent(content_text)), 'B')
  ) STORED,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (project_id, note_date)
);

-- Covers the "recent days" listing and the calendar aggregation, across all
-- of an account's projects (global search in particular).
CREATE INDEX daily_notes_user_date_idx ON daily_notes (user_id, note_date DESC);
CREATE INDEX daily_notes_search_idx ON daily_notes USING GIN (search_vector);

-- Snapshots the account's language at note creation time. better-auth tables
-- ("user") don't go through Kysely: this is the simplest place to do this
-- join without touching the routes. A trigger rather than a value re-read on
-- every write: changing the interface language afterwards shouldn't drift the
-- indexing of a note already written.
CREATE OR REPLACE FUNCTION daily_notes_set_search_language()
RETURNS trigger AS $$
BEGIN
  SELECT CASE "user".language
           WHEN 'en' THEN 'english'::regconfig
           ELSE 'french'::regconfig
         END
  INTO NEW.search_language
  FROM "user"
  WHERE "user".id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
   SET search_path = pg_catalog, public;

CREATE TRIGGER daily_notes_search_language_trigger
  BEFORE INSERT ON daily_notes
  FOR EACH ROW EXECUTE FUNCTION daily_notes_set_search_language();

-- A note's attachments. The row is the source of truth: it carries the
-- original name, the type, and access control (via the note, hence via the
-- user). Storage itself only knows an opaque key and nothing about who owns
-- what.

CREATE TABLE attachments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  note_id     UUID NOT NULL REFERENCES daily_notes(id) ON DELETE CASCADE,
  -- Key in storage. Opaque: only the driver interprets it.
  storage_key TEXT NOT NULL UNIQUE,
  -- Name as deposited by the user, rendered on download.
  filename    TEXT NOT NULL,
  mime_type   TEXT NOT NULL,
  size_bytes  BIGINT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX attachments_note_idx ON attachments (note_id, created_at);

-- A filename isn't prose: a trigram finds a fragment in the middle of a
-- compound word ("latency" in "graph-latency.png"), which a language
-- dictionary would tokenize poorly.
CREATE INDEX attachments_filename_trgm_idx ON attachments
  USING GIN (f_unaccent(filename) gin_trgm_ops);
